# The configuration values can be overriden using springboot mechanics
# a) starting the jar with added config location e.g. "--spring.conf.location=./application.yaml" any values can be overriden in that file
# b) starting the jar with actual values e.g. "--ote.host=192.168.1.2 --mqtt.uri=tcp://192.168.1.3:1883"
ote:
  host: 10.80.81,3
  port: 8080
  user: USER
  password: 123
  delay: 10000 # frequency to poll the OTE
  oids:
    - /1/2/5/119/0
    - /1/2/5/119/1
    - /1/2/5/119/4
    - /1/2/5/119/5
    - /1/2/7/121/0
    - /1/2/7/121/1
    - /1/2/1/125/0
    - /1/2/1/125/1
    - /1/2/1/125/2
    - /1/2/1/125/3
    - /1/2/1/125/4
    - /1/2/1/125/5
    - /1/2/1/125/6
    - /1/2/1/125/7
    - /1/2/1/125/8
    - /1/2/1/125/9
    - /1/2/2/126/0
mqtt:
  uri: tcp://192.168.1.2:1883
  user:
  password:
  basetopic: sensors/heatpump/ote
disabled-logging:
  level:
    root: TRACE
    org.springframework.web: DEBUG
    org.springframework.ws.client.MessageTracing.sent: DEBUG
    org.springframework.ws.server.MessageTracing.sent: DEBUG
    org.springframework.ws.client.MessageTracing.received: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE